name: Wake Up Render
on:
  schedule:
    # This runs every 14 minutes (Render sleeps after 15)
    - cron: '*/10 * * * *'
  workflow_dispatch: # Allows you to run it manually for testing

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Request Website
        run: curl -I https://gripid-tracker.onrender.com